### ISSUE TITLE
[Proposal] Creating a universal TTS Gateway for Wyoming

### ISSUE THREAD

**Issue by mitrokun** [rhasspy/wyoming#18]
If you have time, would you consider creating an integration that allows to integrate various tts from HA into the wyoming pipeline.
Or interact with api of separate tts servers by specifying the format in the integration settings

**Comment by sdetweil** [comment]
my app needs a voice out service
i created a speak event, which takes the text and starts a Synthesize() event which causes AudioChunks, which get forwarded to the snd service

**Comment by sdetweil** [comment]
as those are both done in python for HA, one could create two services, one for each,  without too much trouble

**Comment by mitrokun** [comment]
Looks like any tts in HA can now be added to the voice pipeline.
I'm closing this Issue
