### ISSUE TITLE
Docker Piper - Piper_Length Enviroment Variable doesn't affect the Voices Length Scale

### ISSUE THREAD

**Issue by Gaffers2277** [rhasspy/wyoming#2]
I'm not sure if this is the correct repo for the Wyoming protocol integration in Home Assistant but i'm trying to use the Linux Server docker image for Piper as i need to run Piper on my main server. But when i change the PIPER_LENGTH= 1.0 variable in the docker compose to say 1.5 it doesn't change the length. If i change the length_scale variable in the voices json file from 1.0 to 1.5 it eventually resets back to 1.0. I'm using LinuxServers docker image for Piper and using the Wyoming integration into Home Assistant so maybe the intergation is defaulting to a preset variable. But i cant alter the variables in the integration.

**Comment by synesthesiam** [comment]
This is something you'll have to ask LinuxServers about. I don't maintain that Docker image, so I can't help unfortunately. If you know where their source `Dockerfile` is, I could see if they're passing in the parameter correction.

**Comment by Gaffers2277** [comment]
I spoke to them and i seems like it just took a while for it to change but it eventually did. I will close this issue
