### ISSUE TITLE
why breaking change on audio events? 

### ISSUE THREAD

**Issue by sdetweil** [rhasspy/wyoming#3]
change from audiostop to audio-stop

what useful value is that?

**Comment by synesthesiam** [comment]
I'm confused. The dashes have always been there. The very first commit has them: https://github.com/rhasspy/wyoming/blob/892e01dea82ccb804d93a25dc8eef74a2d4fca37/wyoming/audio.py#L11

How are you using Wyoming?

**Comment by sdetweil** [comment]
weird indeed. I was looking at what I thought was 1.5 (master), but using 1.3 and couldnt get the is_type to work.  at that point I wasn't using the class libs. so this was probably my fault. transcribe however was different. so I ass-umed.

**Comment by sdetweil** [comment]
sorry, didn't answer the second question..making a new asr.

**Comment by sdetweil** [comment]
nodejs didn't have trouble, just needed to explicitly send a newline.  then the server side responded. no info before that

**Comment by sdetweil** [comment]
closing, not an issue
