### ISSUE TITLE
performance suggestion. developer recommendations

### ISSUE THREAD

**Issue by sdetweil** [rhasspy/wyoming#6]
the existing ASR's (fasterwhisper for example) have the handler processing events in workflow order,

describe, transcribe, audiochunk, audio stop, ....

with discrete , if sections
```
if Transcript.is_type(event.type)
```
then another if

two things..

1. the most frequent request (audiochunk) should be first.. 
2. this should be an if/elif/elif,    so stop checking after the 1st successful test

**Comment by synesthesiam** [comment]
I'll make this change in `wyoming-faster-whisper` :+1:
